# Generated by Django 2.1.2 on 2018-11-06 14:52

from django.db import migrations, models
import eshopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='название')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, upload_to=eshopapp.models.generate_filename)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
    ]
